[build]
  command = "vite build --emptyOutDir --minify terser --outDir dist"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18.16.0"
  # Düzenli JS uygulaması için build parametreleri
  VITE_DROP_CONSOLE = "true"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true