[[redirects]]
  from = "/api/*"
  to = "https://modern-ecommerce-fullstack.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"