[build]
  command = "npm install && npm install react-hot-toast @tailwindcss/forms clsx tailwind-merge --save && export NODE_OPTIONS=--max-old-space-size=4096 && CI=false npm run build"
  publish = "dist"

[build.environment]
  VITE_APP_API_URL = "https://modern-ecommerce-fullstack.onrender.com/api"
  VITE_APP_ENV = "production"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://modern-ecommerce-fullstack.onrender.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
    Access-Control-Allow-Credentials = "true"